### ISSUE TITLE
Voice response is empty

### ISSUE THREAD

**Issue by bayescram** [richtier/alexa-voice-service-client#11] opened 2018-07-17 19:57 UTC
I am using Azure text to speech to test this client. I used Azure to generate the voice of the following command with "riff-16khz-16bit-mono-pcm" output format.

    "Alexa, play True or False",
    "Alexa, start Song Quiz",
    "Alexa, ask Baby Groot what time is it",
    "Alexa, Open Eighties Letters",
    "Alexa, ask Question of the Day.",
    "Alexa, Play Jeopardy!",

    "Alexa, play Twenty Questions.",
    "Alexa, open Heads Up! and play Superstars",
    "Alexa, play Geo Quiz",
    "Alexa, Open Alien Simulator"

The first 6 commands return legit response.
I don't know why, but the last 4 commands always return an empty response. 

This may not be related to this repo, but do you happen to know why? 
I tried to change the voice volume and make Azure to speak it slower. None of this worked.

**Comment by richtier** [comment] 2018-07-17 21:07
I'm glad you got good results for the first ones :)

Note you do not need the "alexa" prefix when using this tool - Amazon Voice Service assumes that by the point the audio is uploaded the wake word has already occurred. Try removing that and see if that helps.

Can you please share two of the affected wav files so I can debug. Thanks.

**Comment by 0xorz** [comment] 2018-07-17 23:27
I tried to remove the "Alexa", it didn't help. Actually, it's worse. Only 5 of them give a legit response now.

Here is the link to all the audio files https://drive.google.com/drive/folders/1GQ_XM5P2-qz5SGMhG6rhJn-RjyS0V8BB?usp=sharing

**Comment by richtier** [comment] 2018-07-18 08:22
for "heads up" I get the response "hmm. I do not know that one"

for "twenty questions" it says "here's twenty questions from the games trivia..."

so for me the response is not empty.

what does your code look like? mine looks like this:


```
alexa_client = AlexaVoiceServiceClient(
    client_id='...',
    secret='...',
    refresh_token='...',
)
alexa_client.connect()  # authenticate and other handshaking steps
with open('/home/richtier/Downloads/test.wav', 'rb') as f:
    alexa_response_audio = alexa_client.send_audio_file(f)
with open('./output.wav', 'wb') as f:
    f.write(alexa_response_audio)
```

**Comment by 0xorz** [comment] 2018-07-18 13:49
I wrote a wrapper for a client.

For 
1f8f273eea381aad4bbd8aa9f563409b.wav: "Open Heads Up! and play Superstars", 
548d7b9c60a699410f23168e48e52285.wav: "Play Geo Quiz",
e96466b699d20f65d8d147d751c00379.wav: "Ask Baby Groot what time is it",

My response are just empty.

Others give me legit response.

When I test with the Alexa test tools. I type "Ask baby groot what time is it". Following are the response. Is it possible that this implementation only receives the first response, but sometimes Alexa returns several response for just one question. The same with "Play Geo Quiz"

![image](https://user-images.githubusercontent.com/15514547/42885654-873d471a-8a6f-11e8-81c6-395e72f70b46.png)
![image](https://user-images.githubusercontent.com/15514547/42885717-ba4ae55e-8a6f-11e8-904f-96ab7dce7d45.png)

```python
from avs_client import AlexaVoiceServiceClient

class Alexa:
    def __init__(self, product_id, client_id, client_secret, refresh_token):
        self.product_id = product_id
        self.client_id = client_id
        self.client_secret = client_secret
        self.refresh_token = refresh_token
        self.alexa_client = AlexaVoiceServiceClient(self.client_id, self.client_secret, self.refresh_token)
        self.alexa_client.connect()

    def talk(self, voice_path, response_path=None):
        with open(voice_path, 'rb') as f:
            alexa_response_audio = self.alexa_client.send_audio_file(f)
        
        if response_path is not None and alexa_response_audio is not None:
            with open(response_path, 'wb') as f:
                f.write(alexa_response_audio)
            print('Saved')
        else:
            print('Not Saved')
```

**Comment by richtier** [comment] 2018-07-18 19:39
ah yes - the client does not support multiple responses yet. It currently just returns the first one.

you can stick a breakpoint [here](https://github.com/richtier/alexa-voice-service-client/blob/master/avs_client/avs_client/connection.py#L157) to see if this is the cause: check what `parsed.parts` contains.

**Comment by 0xorz** [comment] 2018-07-19 13:31
Let me try to work on it.  Not sure if Hyper supports Server Push now.

**Comment by richtier** [comment] 2018-07-20 16:36
requirements.txt pins Hyper to a specific version, so we're unaffected by removal of breaking changes.

**Comment by richtier** [comment] 2018-08-14 11:37
@bayescram any progress debugging this?

**Comment by bayescram** [comment] 2018-08-15 21:01
This problem is because this implementation only receives 1 response. I made some changes around the breakpoint you made. Basically, accept all responses and return a list.

**Comment by richtier** [comment] 2018-08-16 22:11
That's great, thanks. I've left some comments on the Pull Request. Let me know if you need assistance with the points raised in the feedback.

**Comment by richtier** [comment] 2018-12-20 23:22
this is now fixed

with latest version you can do

```
from avs_client import AlexaVoiceServiceClient

alexa_client = AlexaVoiceServiceClient(
    client_id='my-client-id',
    secret='my-secret',
    refresh_token='my-refresh-token',
)
alexa_client.connect()  # authenticate and other handshaking steps
with open('./tests/resources/alexa_what_time_is_it.wav', 'rb') as f:
    for directive in alexa_client.send_audio_file(f):
        if directive.name == 'Speak':
            with open(f'./{directive.content_id}.mp3', 'wb') as f:
                f.write(directive.audio_attachment)
```

**Closed by richtier** 2018-12-20 23:22 UTC
