### ISSUE TITLE
Problem getting refresh token

### ISSUE THREAD

**Issue by bayescram** [richtier/alexa-voice-service-client#9] opened 2018-06-27 20:37 UTC
When I run 
`python ./avs_client/refreshtoken/serve.py \
    --device-type-id=enter-device-type-id-here \
    --client-id=enter-client-id-here \
    --client-secret=enter-client-secret-here`

I assume the --device-type-id is the "product id" 
I have added "https://localhost:9000" to allowed origin and added "https://localhost:9000/callback/" to allowed return urls.

But when I run the server.py and go to http:localhost:9000.

It always give me the error.

We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

Hide Details
Error Summary
400 Bad Request
The redirect URI you provided has not been whitelisted for your application. Please add your redirect URI in the 'Allowed Return URLs' section under 'Web Settings' for your Security Profile on Amazon Developer Portal.
Request Details
client_id=amzn1.application-oa2-client.31d6fe43e21d4554bceea25fd258e1d6
scope=alexa%3Aall
scope_data=%7B%22alexa%3Aall%22%3A+%7B%22productID%22%3A+%22bottled_joy%22%2C+%22productInstanceAttributes%22%3A+%7B%22deviceSerialNumber%22%3A+%22001%22%7D%7D%7D
response_type=code
redirect_uri=http%3A%2F%2F1.0.0.127.in-addr.arpa%3A9000%2Fcallback%2F

**Comment by 0xorz** [comment] 2018-06-29 15:12
I observed that the in the URL, the callback URL becomes "http://1.0.0.127.in-addr.arpa:9000/callback/" instead of http://localhost:9000/callback/, so I added the first one into my security profile, It worked. 

Then after finishing the first step, my browser jump to "http://1.0.0.127.in-addr.arpa:9000/callback/?code=ANeLmscGopOgvRciFmBS&scope=alexa%3Aall" which is again not accessable, I manually changed the domain name to localhost again, and I get the refresh token.

I don't know why, but it worked for me.

**Comment by richtier** [comment] 2018-07-17 19:22
thanks for raising the issue. I will try to reproduce it now.

**Comment by richtier** [comment] 2018-07-17 19:37
unfortunately I was unable to reproduce the error.

FWIW, my security profile looks like this:

![image](https://user-images.githubusercontent.com/5485798/42841079-d297f724-8a00-11e8-9702-1f2a6a7ce517.png)

Does the problem still happen for you?

**Comment by 0xorz** [comment] 2018-07-17 19:52
I fixed it by changing the hostname from 1.0.0.127.in-addr.arpa to localhost.

I don't know why my client always calls back to 1.0.0.127.in-addr.arpa instead of localhost.

**Comment by richtier** [comment] 2018-07-17 20:13
can you test on a different device to help determine if the problem is specific to your environment, please?

**Comment by 0xorz** [comment] 2018-07-17 20:24
I tested on my friend's mac, it also has this problem. the call back goes to 1.0.0.127.in-addr.arpa.

**Comment by richtier** [comment] 2018-07-17 21:11
odd. try putting a pdb breakpoint [here](https://github.com/richtier/alexa-voice-service-client/blob/master/avs_client/refreshtoken/handlers.py#L28) and check the value of `self.server.server_name`.

FWIW, when I run `$ host 127.0.0.1` in the shell it tells me `1.0.0.127.in-addr.arpa`

**Comment by bradeckert** [comment] 2018-07-27 02:08
--> `client_device_id` is now `product_id`

**Comment by 0xorz** [comment] 2018-07-27 13:52
Yes, but this is not the problem. I used product_id for device_type_id.

**Comment by The-Gupta** [comment] 2018-07-30 21:35
@0xorz @richtier @bradeckert 
Hey Everyone!
Could someone look at my error and guide?

**Allowed origins** has: 
https://localhost:9875

**Allowed return URLs** has:
http://localhost:9875/callback/
http://BUCKPC:9875/callback/

Command I run: 

> python ./avs_client/refreshtoken/serve.py --device-type-id=Pandit --client-id=amzn1.application-oa2-client.d76af1d2e90442b8b921a35a82815435 --client-secret=a8f54862b9137259dd227b38c93fdf472f6f6634e75ad9a49738a6cc90c28826 -p 9875

As I run, 
```
(base) C:\Anaconda3\Lib\site-packages>python ./avs_client/refreshtoken/serve.py --device-type-id=Pandit --client-id=amzn1.application-oa2-client.d76af1d2e90442b8b921a35a82815435 --client-secret=a8f54862b9137259dd227b38c93fdf472f6f6634e75ad9a49738a6cc90c28826 -p 9875
running server on http://localhost:9875
127.0.0.1 - - [31/Jul/2018 02:37:17] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [31/Jul/2018 02:38:03] "GET / HTTP/1.1" 302 -

```
it says - "running server on http://localhost:9875"

Now, I goto the URL - http://localhost:9875, 
it redirects to [a long link](https://na.account.amazon.com/ap/oa?clientContext=130-6729684-4873743&aToken=Atza%7CIwEBIKpPAUfj9CWTEY8F2WlTT74dAiSxQTk8ntmkUHenhjaNlZp5PSEU6uMLh1DpWaDGhV3oq7IhMTagfQ0fR9GVIiHTADcuGnAbv9msHbT4VYbvR0mtogjapMMInns16NqING1pvjHAFb0qJy5oqOJmGHkQsM68TMO8E2_Ldii5zwRzE2yynvcSBzg_cXld92x_DqeWBo9Di_ICmpFhi9zgHAnK1dO7jMfISmVffCoh4oph_BGs4dTbAcizku802K8NWaP0mMo-W9b2JltibrdIGczUDS9Ifj6NFgA__66-Wqfypx5i8mMbZjxP7euUGQD7dun7yeSTl3Kd59SXcoBW2sC-GPwMn4kLxxHvUZ7-n8JZUfRJCFRmPM6hklvkEKb-46p0f82gCxQIxUCx-1OtGrqE&openid.pape.max_auth_age=1209600&openid.identity=https%3A%2F%2Fwww.amazon.com%2Fap%2Fid%2Famzn1.account.AETF76JEK4K6IBH2NC3EIM3C7AKQ&openid.op_endpoint=https%3A%2F%2Fwww.amazon.com%2Fap%2Fsignin&openid.pape.auth_time=2018-07-30T21%3A24%3A02Z&marketPlaceId=ATVPDKIKX0DER&openid.signed=assoc_handle%2CaToken%2Cclaimed_id%2Cidentity%2Cmode%2Cns%2Cop_endpoint%2Cresponse_nonce%2Creturn_to%2Cns.pape%2Cpape.auth_policies%2Cpape.auth_time%2Csigned&language=en_US&stashKey=eabf0cbc-c4f6-4c18-ba82-15fa80bad378&arb=98a3e14a-a16a-4bef-b0b1-3326aed55ee1&openid.return_to=https%3A%2F%2Fna.account.amazon.com%2Fap%2Foa%3FmarketPlaceId%3DATVPDKIKX0DER%26arb%3D98a3e14a-a16a-4bef-b0b1-3326aed55ee1%26language%3Den_US&openid.assoc_handle=amzn_lwa_na&serial=1&openid.mode=id_res&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.pape.auth_policies=http%3A%2F%2Fschemas.openid.net%2Fpape%2Fpolicies%2F2007%2F06%2Fnone&openid.sig=E0E6%2BMKlMHYdZQYdQG2eI1jgSvrXDDQxRR2U93fjk6JSmAszhhGnq%2BPRaqmkNIbuJ4RvTgzbA9qmp8MpJShJ8dw%2BrBdiCIaRp7dOiE1ChTM1PlCT0GcjPTUqlneXwU3wr8Ch9rJfu9MBo%2BghrfmqAvJMnm5CrdMpxYKtJFNwZeB14i0wTSKaUw0QsZpN9HNeKhr1UpSRq0QwVcrtjg%2F4W0Bramqz0DYHJdZSKHy46RHbaWWR4CujM8neGCall9pSqjiQdKzHWxVRRundlydg%2BO2hmNgjNIp%2BebhQpKhgoLx%2BqqvSeWlOzMw4PvkSceQrA3snHDPVKwBpAPhC%2FJUB4w%3D%3D&openid.claimed_id=https%3A%2F%2Fwww.amazon.com%2Fap%2Fid%2Famzn1.account.AETF76JEK4K6IBH2NC3EIM3C7AKQ&openid.response_nonce=2018-07-30T21%3A24%3A02Z-6961793471330004852&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0)


Where the page asks to - 

`Click 'Allow' to sign in to TheGupta.`

I choose 'Allow.'

I get redirected to another link - http://buckpc:9875/callback/?code=ANEtmnaRYKBGVKdwPzMm&scope=alexa%3Aall [I did try changing the URL by replacing '%3F' with a colon(:), didn't work.]


Where I get ERR_CONNECTION_REFUSED

> This site can’t be reached
> buckpc refused to connect.
> Search Google for buck pc 9875 callback
> ERR_CONNECTION_REFUSED


IF YOU'RE NOT SURE ABOUT THE FIX, COULD YOU TELL AN ALTERNATIVE TO GENERATE THE TOKEN?

**Comment by The-Gupta** [comment] 2018-08-01 06:35
It works when I specify address also.

> python ./avs_client/refreshtoken/serve.py --device-type-id=Pandit --client-id=amzn1.application-oa2-client.d76af1d2e90442b8b921a35a82815435 --client-secret=a8f54862b9137259dd227b38c93fdf472f6f6634e75ad9a49738a6cc90c28826 **-a BUCKPC** -p 9875

I think it's because it redirects to the PC-name's path not to localhost.

**Comment by common83** [comment] 2018-08-03 07:36
it reproduce the same problem. Using localhost throws error,using PC(windows) name will work.

**Comment by richtier** [comment] 2018-08-14 11:33
seems to be a common problem :)

I will make update a release where we explicitly defined the callback url as a flag e.g,  

```
python ./avs_client/refreshtoken/serve.py 
    --device-type-id=Pandit
    --client-id={client_id} 
    --client-secret={secret}
    --callback_url=http://localhost:8000/callback/
```

**Comment by richtier** [comment] 2018-08-14 11:36
@The-Gupta it looks like you've shared your oauth2 secret

If I were you I would take action to disable those secrets  :)

**Comment by richtier** [comment] 2018-08-16 21:42
problem should be fixed

`pip install avs_client==0.7.1`

no need to change how `./avs_client/refreshtoken/serve.py` is executed it should just work.

**Closed** 2018-08-16 21:42 UTC

**Comment by Prskriti** [comment] 2018-10-19 10:55
Facing similar issue of 404 Bad request. Please guide me how to resolve this issue

**Comment by Prskriti** [comment] 2018-10-19 11:38
I have tried these arguments set also but nothing seems to help
python ./avs_client/refreshtoken/serve.py 
    --device-type-id=Pandit
    --client-id={client_id} 
    --client-secret={secret}
    --callback_url=http://localhost:8000/callback/

**Comment by The-Gupta** [comment] 2018-10-19 11:52
@Prskriti , Is _Pandit_ your Product ID that you entered in Product Information, as **device-type-id** is the Product ID ? See [here ](https://github.com/richtier/alexa-voice-service-client#refresh-token).

**Comment by Prskriti** [comment] 2018-10-19 12:56
@The-Gupta Nope I entered my device type id

**Comment by Prskriti** [comment] 2018-10-19 13:09
Each and every time I am getting amazon error page. 
We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

Hide Details
Error Summary
400 Bad Request
The redirect URI you provided has not been whitelisted for your application. Please add your redirect URI in the 'Allowed Return URLs' section under 'Web Settings' for your Security Profile on Amazon Developer Portal.

**Comment by richtier** [comment] 2018-11-10 17:39
Please open a new issue as this problem is unrelated to this closed issue.
